import { VoiceLanguageMenuSchema } from "../language/voice-language-menu.js";

// This is the India flagship entrypoint default, not a core language boundary.
// Another deployment can replace the injected menu without changing teaching,
// persistence, curriculum, or telephony state-machine code.
export const DEFAULT_VOICE_LANGUAGE_MENU = VoiceLanguageMenuSchema.parse([
  {
    key: "1",
    languageMode: "en",
    displayName: "English",
    selectionPrompt: "For English, press 1.",
    identityPrompt: "Welcome to Continuum. What name would you like me to use for you?",
    languageAliases: ["English"],
    noLearnerCodeAliases: ["no", "no code", "i do not have a code", "i don't have a code"],
  },
  {
    key: "2",
    languageMode: "hi",
    displayName: "Hindi",
    selectionPrompt: "हिंदी के लिए 2 दबाएँ।",
    identityPrompt: "कॉन्टिन्यूअम में आपका स्वागत है। मैं आपको किस नाम से बुलाऊँ?",
    languageAliases: ["Hindi", "हिंदी", "हिन्दी"],
    noLearnerCodeAliases: ["नहीं", "नही", "कोड नहीं", "मेरे पास कोड नहीं", "no"],
  },
  {
    key: "3",
    languageMode: "es",
    displayName: "Español",
    selectionPrompt: "Para español, oprime 3.",
    identityPrompt: "Bienvenido a Continuum. ¿Qué nombre quieres que use para ti?",
    languageAliases: ["Spanish", "español", "espanol"],
    noLearnerCodeAliases: ["no", "no tengo código", "no tengo codigo", "sin código", "sin codigo"],
  },
  {
    key: "4",
    languageMode: "fr",
    displayName: "Français",
    selectionPrompt: "Pour le français, appuyez sur 4.",
    identityPrompt: "Bienvenue sur Continuum. Quel nom veux-tu que j'utilise?",
    languageAliases: ["French", "français", "francais"],
    noLearnerCodeAliases: ["non", "je n'ai pas de code", "pas de code"],
  },
  {
    key: "5",
    languageMode: "sw",
    displayName: "Kiswahili",
    selectionPrompt: "Kwa Kiswahili, bonyeza tano, nambari 5.",
    identityPrompt: "Karibu Continuum. Ungependa nikuitaje?",
    languageAliases: ["Swahili", "Kiswahili"],
    noLearnerCodeAliases: ["hapana", "sina msimbo", "sina nambari", "sina code", "no"],
  },
  {
    key: "6",
    languageMode: "ta",
    displayName: "தமிழ்",
    selectionPrompt: "தமிழுக்கு 6 அழுத்தவும்.",
    identityPrompt: "Continuum-க்கு வரவேற்கிறோம். உங்களை எந்தப் பெயரில் அழைக்கலாம்?",
    languageAliases: ["Tamil", "தமிழ்"],
    noLearnerCodeAliases: ["இல்லை", "குறியீடு இல்லை", "கோடு இல்லை", "no"],
  },
  {
    key: "7",
    languageMode: "bn",
    displayName: "বাংলা",
    selectionPrompt: "বাংলার জন্য 7 চাপুন।",
    identityPrompt: "Continuum-এ স্বাগতম। আমি তোমাকে কোন নামে ডাকব?",
    languageAliases: ["Bengali", "Bangla", "বাংলা"],
    noLearnerCodeAliases: ["না", "কোড নেই", "no"],
  },
  {
    key: "8",
    languageMode: "ar",
    displayName: "العربية",
    selectionPrompt: "للعربية اضغط 8.",
    identityPrompt: "مرحبًا بك في Continuum. ما الاسم الذي تريدني أن أناديك به؟",
    languageAliases: ["Arabic", "العربية", "عربي"],
    noLearnerCodeAliases: ["لا", "ليس لدي رمز", "ما عندي رمز", "no"],
  },
  {
    key: "9",
    languageMode: "ur",
    displayName: "اردو",
    selectionPrompt: "اردو کے لیے 9 دبائیں۔",
    identityPrompt: "Continuum میں خوش آمدید۔ میں آپ کو کس نام سے پکاروں؟",
    languageAliases: ["Urdu", "اردو"],
    noLearnerCodeAliases: ["نہیں", "کوڈ نہیں", "میرے پاس کوڈ نہیں", "no"],
  },
]);
